language: rust
rust: stable
sudo: required
dist: trusty

git:
  depth: 1

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
           ALT=i686-unknown-linux-gnu

  exclude:
    - rust: stable

before_script:
  - rustup target add $ALT
script:
  - cargo test --features=deny-warnings --test testsuite -- can_not_mix_doc_tests_and_regular_tests

addons:
  apt:
    packages:
      - gcc-multilib
