name: CI
on:
  push:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - name: Test
        run: |
          for i in {1..50}
          do
            cargo test --test testsuite -- package
          done
