name: Index Squash
on:
  schedule:
    - cron:  '45 16 * * *'
  workflow_dispatch:

jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ehuss/crates.io-index
        # token: ${{ secrets.crates_io_token }}
    - run: ci/squash.sh
      # env:
      #   CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}
